---
# Variables shared across all remote_testing hosts

# admin is the default user for the AWS Debian Jessie AMI
ansible_user: admin

# If you are the picoCTF platform remotely you may have a private repository.
# You likely want to configure a read only deployment key, or a machine key.
private_repo: True
deploy_private_key_file: "deploy.picoCTF.private-repo.id_rsa"

##
# Web settings (env specific)
##
web_fqdn: "{{ hostvars['remote_testing_web']['ansible_host'] }}"
nginx_server_name: "{{ web_fqdn }}"
web_address: "{{ web_fqdn }}"
web_address_internal: "http://10.0.1.10"
htpasswd_accounts: "{{ vault_htpasswd_accounts }}"

flask_app_server_name: "{{ web_fqdn }}"
flask_app_cookie_domain: "\"{{ web_fqdn }}\""
flask_app_secret_key: "{{ vault_flask_app_secret_key }}"

# optional web automation
enable_basic_auth:      True
auto_add_shell:         True
auto_load_problems:     True
auto_start_competition: True


###
# Shell Settings (env specific)
###
shell_hostname: "{{ hostvars['remote_testing_shell']['ansible_host'] }}"
shell_name: Remote-Testing-Shell
shell_host: "{{ shell_hostname }}"
shell_user: "{{ ansible_user }}"

# These sensitive variables are loaded from an ansible-vault encrypted file
# This is an example of a secure way to deploy your configuration secrets
# For this public example the vault password is "pico" so you can see this in
# action. You are highly encouraged to rekey this file prior to use.
# For more information: http://docs.ansible.com/ansible/playbooks_vault.html
shell_pass: "{{ vault_shell_pass }}"
shell_admin_password_crypt: "{{ vault_shell_admin_password_crypt }}"
shell_manager_deploy_secret: " {{ vault_shell_manager_deploy_secret }}"


##
# Database settings (env specific)
##
on_aws: True
db_private_ip: 127.0.0.1
mongodb_conf_auth: True
picoAdmin_db_password:  "insecure-password"
picoWeb_db_password:    "insecure-password"

env_db_users:
  - {
    name: picoWeb,
    password: "{{ picoWeb_db_password }}",
    roles: readWrite,
    database: "{{ db_name }}"
    }
mongodb_web_user: "picoWeb"

##
# Problem Settings
# use role defaults (example problems and challenge-sampler bundle)
##
